/**
 * GetPaidRx - Pharmacy Dashboard: Underpayment Detection
 * 
 * Features:
 * - Detect underpayments (NADAC vs actual reimbursement)
 * - Auto-generate appeal letters
 * - Revenue recovery tracker ($$ saved/recovered)
 * - Batch claim analyzer (upload CSV → flag all underpayments)
 */

export interface Claim {
  claimId: string;
  ndc: string;
  drugName: string;
  quantity: number;
  dateDispensed: string;
  reimbursement: number;
  nadacPrice?: number;
  isUnderpaid?: boolean;
  underpaymentAmount?: number;
}

export interface AppealLetter {
  claimId: string;
  payer: string;
  letterText: string;
  generatedAt: string;
}

export interface RecoveryStats {
  totalClaims: number;
  underpaidClaims: number;
  totalUnderpayment: number;
  appealsSubmitted: number;
  amountRecovered: number;
  successRate: number; // percentage
}

export class UnderpaymentDetector {
  private nadacDatabase: Map<string, number>;

  constructor(nadacDatabase: Map<string, number>) {
    this.nadacDatabase = nadacDatabase;
  }

  // Analyze single claim for underpayment
  analyzeClaim(claim: Claim): Claim {
    const nadacPrice = this.nadacDatabase.get(claim.ndc);

    if (!nadacPrice) {
      console.warn(`⚠️ No NADAC price found for NDC ${claim.ndc}`);
      return { ...claim, isUnderpaid: false };
    }

    const expectedReimbursement = nadacPrice * claim.quantity;
    const actualReimbursement = claim.reimbursement;

    // Flag if actual < 90% of expected (allow 10% tolerance for dispensing fees)
    const isUnderpaid = actualReimbursement < expectedReimbursement * 0.9;
    const underpaymentAmount = isUnderpaid 
      ? expectedReimbursement - actualReimbursement 
      : 0;

    return {
      ...claim,
      nadacPrice,
      isUnderpaid,
      underpaymentAmount
    };
  }

  // Batch analyze claims from CSV
  async analyzeBatchClaims(csvData: string): Promise<Claim[]> {
    const lines = csvData.split('\n').filter(l => l.trim());
    const headers = lines[0].split(',');

    const claims: Claim[] = lines.slice(1).map(line => {
      const values = line.split(',');
      return {
        claimId: values[0],
        ndc: values[1],
        drugName: values[2],
        quantity: parseInt(values[3]),
        dateDispensed: values[4],
        reimbursement: parseFloat(values[5])
      };
    });

    // Analyze each claim
    const analyzed = claims.map(c => this.analyzeClaim(c));

    const underpaidCount = analyzed.filter(c => c.isUnderpaid).length;
    const totalUnderpayment = analyzed.reduce((sum, c) => sum + (c.underpaymentAmount || 0), 0);

    console.log(`📊 Batch Analysis Complete:`);
    console.log(`   Total Claims: ${analyzed.length}`);
    console.log(`   Underpaid: ${underpaidCount} (${(underpaidCount / analyzed.length * 100).toFixed(1)}%)`);
    console.log(`   Total Underpayment: $${totalUnderpayment.toFixed(2)}`);

    return analyzed;
  }

  // Generate appeal letter
  generateAppealLetter(claim: Claim, payer: string = 'Insurance Company'): AppealLetter {
    if (!claim.isUnderpaid) {
      throw new Error('Cannot appeal non-underpaid claim');
    }

    const letterText = `
PHARMACY REIMBURSEMENT APPEAL

Date: ${new Date().toLocaleDateString()}
Claim ID: ${claim.claimId}
Payer: ${payer}

Dear ${payer} Claims Department,

We are writing to appeal the underpayment of the above-referenced claim for the following prescription:

Drug: ${claim.drugName}
NDC: ${claim.ndc}
Quantity: ${claim.quantity}
Date Dispensed: ${claim.dateDispensed}

ISSUE:
The reimbursement provided ($${claim.reimbursement.toFixed(2)}) is below the National Average Drug Acquisition Cost (NADAC) benchmark.

NADAC PRICING:
- NADAC Price per Unit: $${claim.nadacPrice!.toFixed(4)}
- Expected Reimbursement (${claim.quantity} units): $${(claim.nadacPrice! * claim.quantity).toFixed(2)}
- Actual Reimbursement: $${claim.reimbursement.toFixed(2)}
- Underpayment Amount: $${claim.underpaymentAmount!.toFixed(2)}

SUPPORTING DOCUMENTATION:
1. NADAC database reference (CMS source, updated ${new Date().toLocaleDateString()})
2. Pharmacy invoice showing acquisition cost
3. Claim submission records

REQUESTED ACTION:
We respectfully request a re-adjudication of this claim to reflect the appropriate reimbursement based on NADAC pricing plus applicable dispensing fees.

Expected Additional Payment: $${claim.underpaymentAmount!.toFixed(2)}

Please respond within 30 days per your provider agreement timelines.

Sincerely,
[Pharmacy Name]
[License Number]
[Contact Information]

---
Generated by GetPaidRx - Pharmacy Revenue Recovery Platform
    `.trim();

    return {
      claimId: claim.claimId,
      payer,
      letterText,
      generatedAt: new Date().toISOString()
    };
  }

  // Batch generate appeals for all underpaid claims
  generateBatchAppeals(claims: Claim[], payer: string = 'Insurance Company'): AppealLetter[] {
    return claims
      .filter(c => c.isUnderpaid)
      .map(c => this.generateAppealLetter(c, payer));
  }

  // Track recovery stats
  calculateRecoveryStats(
    claims: Claim[],
    appealsSubmitted: number,
    amountRecovered: number
  ): RecoveryStats {
    const underpaidClaims = claims.filter(c => c.isUnderpaid);
    const totalUnderpayment = underpaidClaims.reduce((sum, c) => sum + (c.underpaymentAmount || 0), 0);
    const successRate = appealsSubmitted > 0 
      ? (amountRecovered / totalUnderpayment) * 100 
      : 0;

    return {
      totalClaims: claims.length,
      underpaidClaims: underpaidClaims.length,
      totalUnderpayment,
      appealsSubmitted,
      amountRecovered,
      successRate
    };
  }

  // Export underpaid claims to CSV
  exportUnderpaidToCSV(claims: Claim[]): string {
    const underpaid = claims.filter(c => c.isUnderpaid);
    
    let csv = 'Claim ID,NDC,Drug Name,Quantity,Date Dispensed,Reimbursement,NADAC Price,Expected Reimbursement,Underpayment Amount\n';
    
    underpaid.forEach(c => {
      const expected = (c.nadacPrice || 0) * c.quantity;
      csv += `${c.claimId},${c.ndc},"${c.drugName}",${c.quantity},${c.dateDispensed},${c.reimbursement},${c.nadacPrice},${expected.toFixed(2)},${c.underpaymentAmount}\n`;
    });

    return csv;
  }
}

// React Dashboard Component
export function PharmacyDashboard() {
  const [claims, setClaims] = React.useState<Claim[]>([]);
  const [stats, setStats] = React.useState<RecoveryStats | null>(null);
  const [selectedClaim, setSelectedClaim] = React.useState<Claim | null>(null);
  const [appealLetter, setAppealLetter] = React.useState<AppealLetter | null>(null);

  const detector = new UnderpaymentDetector(new Map()); // Load NADAC data

  const handleUploadCSV = async (file: File) => {
    const text = await file.text();
    const analyzed = await detector.analyzeBatchClaims(text);
    setClaims(analyzed);

    const recoveryStats = detector.calculateRecoveryStats(analyzed, 0, 0);
    setStats(recoveryStats);
  };

  const handleGenerateAppeal = (claim: Claim) => {
    const letter = detector.generateAppealLetter(claim, 'Medicare');
    setAppealLetter(letter);
  };

  const handleExportUnderpaid = () => {
    const csv = detector.exportUnderpaidToCSV(claims);
    const blob = new Blob([csv], { type: 'text/csv' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `underpaid-claims-${Date.now()}.csv`;
    a.click();
  };

  return (
    <div className="pharmacy-dashboard">
      <h1>💰 Pharmacy Underpayment Dashboard</h1>

      <input 
        type="file" 
        accept=".csv"
        onChange={(e) => e.target.files?.[0] && handleUploadCSV(e.target.files[0])}
      />

      {stats && (
        <div className="stats">
          <h2>📊 Recovery Stats</h2>
          <p>Total Claims: {stats.totalClaims}</p>
          <p>Underpaid: {stats.underpaidClaims} ({(stats.underpaidClaims / stats.totalClaims * 100).toFixed(1)}%)</p>
          <p>Total Underpayment: ${stats.totalUnderpayment.toFixed(2)}</p>
          <button onClick={handleExportUnderpaid}>Export Underpaid Claims</button>
        </div>
      )}

      <div className="claims-list">
        <h2>⚠️ Underpaid Claims</h2>
        <ul>
          {claims.filter(c => c.isUnderpaid).map(claim => (
            <li key={claim.claimId}>
              {claim.drugName} ({claim.ndc}) - Underpaid by ${claim.underpaymentAmount?.toFixed(2)}
              <button onClick={() => handleGenerateAppeal(claim)}>Generate Appeal</button>
            </li>
          ))}
        </ul>
      </div>

      {appealLetter && (
        <div className="appeal-letter">
          <h2>📄 Appeal Letter</h2>
          <pre>{appealLetter.letterText}</pre>
          <button onClick={() => navigator.clipboard.writeText(appealLetter.letterText)}>
            Copy to Clipboard
          </button>
        </div>
      )}
    </div>
  );
}
